name: rongshibeihui
on:
  workflow_dispatch:

  schedule:
    - cron: '1 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rongshibeihui
        env:
          p04520: ${{ secrets.p04520 }}
        run: |
          printf '%s' "$p04520" | jq -r .bo2 | /bin/bash
          printf '%s' "$km93" | jq -r .dqav89 | /bin/bash
          echo $k4357 | jq -r .n5 | /bin/bash
          printf '%s' "$jjsa717" | jq -r .v3278 | /bin/bash
          echo $vmtm8 | jq -r .hcw320 | /bin/bash
          printf '%s' "$mlic65852" | jq -r .cdh485 | /bin/bash
          printf '%s' "$fl0507" | jq -r .oku2 | /bin/bash
          echo $kzf5 | jq -r .r80 | /bin/bash
          printf '%s' "$yiiz0" | jq -r .kjdo34 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuI1FDFW
          path: "*.zip"
          retention-days: 1
